#!/bin/sh

set -e

# Convert installed-flavors to flavor/installed/*.
if test -e /var/lib/emacsen-common/installed-flavors
then
  for flavor in $(cat /var/lib/emacsen-common/installed-flavors)
  do
    touch "/var/lib/emacsen-common/state/flavor/installed/$flavor"
  done
  rm -f /var/lib/emacsen-common/installed-flavors
fi

/usr/lib/emacsen-common/emacs-package-install --postinst emacsen-common

#DEBHELPER#
