#!/bin/sh

set -e

/usr/lib/emacsen-common/emacs-package-remove emacsen-common

(rmdir /usr/local/share/emacs/site-lisp 2>/dev/null && \
 rmdir /usr/local/share/emacs           2>/dev/null) || true

exit 0
